In [1]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.compose import make_column_selector
import pandas as pd
import numpy as np

In [2]:
#sample dataframe used for example
data = [[7.2500, 'S', 'male', 22.0], [71.29, 'C', 'female', 38.0], [9, 'S', 'female', 26.0], [33, 'S', 'female', 26.0], [33, 'C', 'male', 26.0]] 
  
# Create the pandas DataFrame 
df = pd.DataFrame(data, columns = ['Fare', 'Embarked', 'Sex', 'Age']) 
  
# print dataframe. 
df 


Fare Embarked     Sex   Age
0   7.25        S    male  22.0
1  71.29        C  female  38.0
2   9.00        S  female  26.0
3  33.00        S  female  26.0
4  33.00        C    male  26.0

In [4]:
ohe = OneHotEncoder()

In [12]:
# Seven Ways to produce same results
#column name
ct_df1 = make_column_transformer((ohe, ['Embarked', 'Sex']))
#column index
ct_df2 = make_column_transformer((ohe, [1,2]))
#column slice
ct_df3 = make_column_transformer((ohe, slice(1,3)))
#column boolean
ct_df4 = make_column_transformer((ohe, [False, True, True, False]))
#column name pattern
ct_df5 = make_column_transformer((ohe, make_column_selector(pattern= 'E|S')))
#column data type categorical include
ct_df6 = make_column_transformer((ohe, make_column_selector(dtype_include=object)))
#column data type numberical exclude
ct_df7 = make_column_transformer((ohe, make_column_selector(dtype_exclude='number')))    

In [13]:
ct_df1.fit_transform(df)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.]])

In [15]:
ct_df2.fit_transform(df)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.]])

In [16]:
ct_df3.fit_transform(df)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.]])

In [17]:
ct_df4.fit_transform(df)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.]])

In [18]:
ct_df5.fit_transform(df)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.]])

In [19]:
ct_df6.fit_transform(df)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.]])

In [20]:
ct_df7.fit_transform(df)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.]])